# Generated by Django 3.2.19 on 2023-08-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
