# Generated by Django 3.2.19 on 2023-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='funds',
            field=models.FloatField(default=0),
        ),
    ]
